AWSTemplateFormatVersion: "2010-09-09"
Description: Test
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hr-test-12345
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow 
            Action: 
            - "s3:GetObject"
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref Bucket
                - /*
            Principal: '*'

      